/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Deduction
 */
public class DeductionTest {
    private final Deduction model = new Deduction();

    /**
     * Model tests for Deduction
     */
    @Test
    public void testDeduction() {
        // TODO: test Deduction
    }

    /**
     * Test the property 'agency'
     */
    @Test
    public void agencyTest() {
        // TODO: test agency
    }

    /**
     * Test the property 'annualMaximum'
     */
    @Test
    public void annualMaximumTest() {
        // TODO: test annualMaximum
    }

    /**
     * Test the property 'calcCode'
     */
    @Test
    public void calcCodeTest() {
        // TODO: test calcCode
    }

    /**
     * Test the property 'caseNo'
     */
    @Test
    public void caseNoTest() {
        // TODO: test caseNo
    }

    /**
     * Test the property 'costCenter1'
     */
    @Test
    public void costCenter1Test() {
        // TODO: test costCenter1
    }

    /**
     * Test the property 'costCenter2'
     */
    @Test
    public void costCenter2Test() {
        // TODO: test costCenter2
    }

    /**
     * Test the property 'costCenter3'
     */
    @Test
    public void costCenter3Test() {
        // TODO: test costCenter3
    }

    /**
     * Test the property 'dcode'
     */
    @Test
    public void dcodeTest() {
        // TODO: test dcode
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'fipsCode'
     */
    @Test
    public void fipsCodeTest() {
        // TODO: test fipsCode
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'goal'
     */
    @Test
    public void goalTest() {
        // TODO: test goal
    }

    /**
     * Test the property 'isSelfInsuredPlan'
     */
    @Test
    public void isSelfInsuredPlanTest() {
        // TODO: test isSelfInsuredPlan
    }

    /**
     * Test the property 'loanFirstPaymentDate401K'
     */
    @Test
    public void loanFirstPaymentDate401KTest() {
        // TODO: test loanFirstPaymentDate401K
    }

    /**
     * Test the property 'loanIssueDate401K'
     */
    @Test
    public void loanIssueDate401KTest() {
        // TODO: test loanIssueDate401K
    }

    /**
     * Test the property 'loanNumber'
     */
    @Test
    public void loanNumberTest() {
        // TODO: test loanNumber
    }

    /**
     * Test the property 'maximum'
     */
    @Test
    public void maximumTest() {
        // TODO: test maximum
    }

    /**
     * Test the property 'medicalSupport'
     */
    @Test
    public void medicalSupportTest() {
        // TODO: test medicalSupport
    }

    /**
     * Test the property 'minimum'
     */
    @Test
    public void minimumTest() {
        // TODO: test minimum
    }

    /**
     * Test the property 'miscInfo'
     */
    @Test
    public void miscInfoTest() {
        // TODO: test miscInfo
    }

    /**
     * Test the property 'paidTowardsGoal'
     */
    @Test
    public void paidTowardsGoalTest() {
        // TODO: test paidTowardsGoal
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'reportTerminated'
     */
    @Test
    public void reportTerminatedTest() {
        // TODO: test reportTerminated
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'stateAbbrev'
     */
    @Test
    public void stateAbbrevTest() {
        // TODO: test stateAbbrev
    }

}
