/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Earning
 */
public class EarningTest {
    private final Earning model = new Earning();

    /**
     * Model tests for Earning
     */
    @Test
    public void testEarning() {
        // TODO: test Earning
    }

    /**
     * Test the property 'agency'
     */
    @Test
    public void agencyTest() {
        // TODO: test agency
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'annualMaximum'
     */
    @Test
    public void annualMaximumTest() {
        // TODO: test annualMaximum
    }

    /**
     * Test the property 'calculationCode'
     */
    @Test
    public void calculationCodeTest() {
        // TODO: test calculationCode
    }

    /**
     * Test the property 'costCenter1'
     */
    @Test
    public void costCenter1Test() {
        // TODO: test costCenter1
    }

    /**
     * Test the property 'costCenter2'
     */
    @Test
    public void costCenter2Test() {
        // TODO: test costCenter2
    }

    /**
     * Test the property 'costCenter3'
     */
    @Test
    public void costCenter3Test() {
        // TODO: test costCenter3
    }

    /**
     * Test the property 'earningCode'
     */
    @Test
    public void earningCodeTest() {
        // TODO: test earningCode
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'goal'
     */
    @Test
    public void goalTest() {
        // TODO: test goal
    }

    /**
     * Test the property 'hoursOrUnits'
     */
    @Test
    public void hoursOrUnitsTest() {
        // TODO: test hoursOrUnits
    }

    /**
     * Test the property 'isSelfInsured'
     */
    @Test
    public void isSelfInsuredTest() {
        // TODO: test isSelfInsured
    }

    /**
     * Test the property 'jobCode'
     */
    @Test
    public void jobCodeTest() {
        // TODO: test jobCode
    }

    /**
     * Test the property 'miscellaneousInfo'
     */
    @Test
    public void miscellaneousInfoTest() {
        // TODO: test miscellaneousInfo
    }

    /**
     * Test the property 'paidTowardsGoal'
     */
    @Test
    public void paidTowardsGoalTest() {
        // TODO: test paidTowardsGoal
    }

    /**
     * Test the property 'payPeriodMaximum'
     */
    @Test
    public void payPeriodMaximumTest() {
        // TODO: test payPeriodMaximum
    }

    /**
     * Test the property 'payPeriodMinimum'
     */
    @Test
    public void payPeriodMinimumTest() {
        // TODO: test payPeriodMinimum
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'rateCode'
     */
    @Test
    public void rateCodeTest() {
        // TODO: test rateCode
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

}
