/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Employee
 */
public class EmployeeTest {
    private final Employee model = new Employee();

    /**
     * Model tests for Employee
     */
    @Test
    public void testEmployee() {
        // TODO: test Employee
    }

    /**
     * Test the property 'additionalDirectDeposit'
     */
    @Test
    public void additionalDirectDepositTest() {
        // TODO: test additionalDirectDeposit
    }

    /**
     * Test the property 'additionalRate'
     */
    @Test
    public void additionalRateTest() {
        // TODO: test additionalRate
    }

    /**
     * Test the property 'benefitSetup'
     */
    @Test
    public void benefitSetupTest() {
        // TODO: test benefitSetup
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'companyFEIN'
     */
    @Test
    public void companyFEINTest() {
        // TODO: test companyFEIN
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'customBooleanFields'
     */
    @Test
    public void customBooleanFieldsTest() {
        // TODO: test customBooleanFields
    }

    /**
     * Test the property 'customDateFields'
     */
    @Test
    public void customDateFieldsTest() {
        // TODO: test customDateFields
    }

    /**
     * Test the property 'customDropDownFields'
     */
    @Test
    public void customDropDownFieldsTest() {
        // TODO: test customDropDownFields
    }

    /**
     * Test the property 'customNumberFields'
     */
    @Test
    public void customNumberFieldsTest() {
        // TODO: test customNumberFields
    }

    /**
     * Test the property 'customTextFields'
     */
    @Test
    public void customTextFieldsTest() {
        // TODO: test customTextFields
    }

    /**
     * Test the property 'departmentPosition'
     */
    @Test
    public void departmentPositionTest() {
        // TODO: test departmentPosition
    }

    /**
     * Test the property 'disabilityDescription'
     */
    @Test
    public void disabilityDescriptionTest() {
        // TODO: test disabilityDescription
    }

    /**
     * Test the property 'emergencyContacts'
     */
    @Test
    public void emergencyContactsTest() {
        // TODO: test emergencyContacts
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'ethnicity'
     */
    @Test
    public void ethnicityTest() {
        // TODO: test ethnicity
    }

    /**
     * Test the property 'federalTax'
     */
    @Test
    public void federalTaxTest() {
        // TODO: test federalTax
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'homeAddress'
     */
    @Test
    public void homeAddressTest() {
        // TODO: test homeAddress
    }

    /**
     * Test the property 'isHighlyCompensated'
     */
    @Test
    public void isHighlyCompensatedTest() {
        // TODO: test isHighlyCompensated
    }

    /**
     * Test the property 'isSmoker'
     */
    @Test
    public void isSmokerTest() {
        // TODO: test isSmoker
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'localTax'
     */
    @Test
    public void localTaxTest() {
        // TODO: test localTax
    }

    /**
     * Test the property 'mainDirectDeposit'
     */
    @Test
    public void mainDirectDepositTest() {
        // TODO: test mainDirectDeposit
    }

    /**
     * Test the property 'maritalStatus'
     */
    @Test
    public void maritalStatusTest() {
        // TODO: test maritalStatus
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'nonPrimaryStateTax'
     */
    @Test
    public void nonPrimaryStateTaxTest() {
        // TODO: test nonPrimaryStateTax
    }

    /**
     * Test the property 'ownerPercent'
     */
    @Test
    public void ownerPercentTest() {
        // TODO: test ownerPercent
    }

    /**
     * Test the property 'preferredName'
     */
    @Test
    public void preferredNameTest() {
        // TODO: test preferredName
    }

    /**
     * Test the property 'primaryPayRate'
     */
    @Test
    public void primaryPayRateTest() {
        // TODO: test primaryPayRate
    }

    /**
     * Test the property 'primaryStateTax'
     */
    @Test
    public void primaryStateTaxTest() {
        // TODO: test primaryStateTax
    }

    /**
     * Test the property 'priorLastName'
     */
    @Test
    public void priorLastNameTest() {
        // TODO: test priorLastName
    }

    /**
     * Test the property 'salutation'
     */
    @Test
    public void salutationTest() {
        // TODO: test salutation
    }

    /**
     * Test the property 'ssn'
     */
    @Test
    public void ssnTest() {
        // TODO: test ssn
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

    /**
     * Test the property 'taxSetup'
     */
    @Test
    public void taxSetupTest() {
        // TODO: test taxSetup
    }

    /**
     * Test the property 'veteranDescription'
     */
    @Test
    public void veteranDescriptionTest() {
        // TODO: test veteranDescription
    }

    /**
     * Test the property 'webTime'
     */
    @Test
    public void webTimeTest() {
        // TODO: test webTime
    }

    /**
     * Test the property 'workAddress'
     */
    @Test
    public void workAddressTest() {
        // TODO: test workAddress
    }

    /**
     * Test the property 'workEligibility'
     */
    @Test
    public void workEligibilityTest() {
        // TODO: test workEligibility
    }

}
