/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocalTax
 */
public class LocalTaxTest {
    private final LocalTax model = new LocalTax();

    /**
     * Model tests for LocalTax
     */
    @Test
    public void testLocalTax() {
        // TODO: test LocalTax
    }

    /**
     * Test the property 'exemptions'
     */
    @Test
    public void exemptionsTest() {
        // TODO: test exemptions
    }

    /**
     * Test the property 'exemptions2'
     */
    @Test
    public void exemptions2Test() {
        // TODO: test exemptions2
    }

    /**
     * Test the property 'filingStatus'
     */
    @Test
    public void filingStatusTest() {
        // TODO: test filingStatus
    }

    /**
     * Test the property 'residentPSD'
     */
    @Test
    public void residentPSDTest() {
        // TODO: test residentPSD
    }

    /**
     * Test the property 'taxCode'
     */
    @Test
    public void taxCodeTest() {
        // TODO: test taxCode
    }

    /**
     * Test the property 'workPSD'
     */
    @Test
    public void workPSDTest() {
        // TODO: test workPSD
    }

}
