/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewAdditionalDirectDeposit
 */
public class NewAdditionalDirectDepositTest {
    private final NewAdditionalDirectDeposit model = new NewAdditionalDirectDeposit();

    /**
     * Model tests for NewAdditionalDirectDeposit
     */
    @Test
    public void testNewAdditionalDirectDeposit() {
        // TODO: test NewAdditionalDirectDeposit
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'routingNumber'
     */
    @Test
    public void routingNumberTest() {
        // TODO: test routingNumber
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'amountType'
     */
    @Test
    public void amountTypeTest() {
        // TODO: test amountType
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'blockSpecial'
     */
    @Test
    public void blockSpecialTest() {
        // TODO: test blockSpecial
    }

    /**
     * Test the property 'nameOnAccount'
     */
    @Test
    public void nameOnAccountTest() {
        // TODO: test nameOnAccount
    }

    /**
     * Test the property 'skipPreNote'
     */
    @Test
    public void skipPreNoteTest() {
        // TODO: test skipPreNote
    }

    /**
     * Test the property 'preNoteDate'
     */
    @Test
    public void preNoteDateTest() {
        // TODO: test preNoteDate
    }

}
