/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewStateTax
 */
public class NewStateTaxTest {
    private final NewStateTax model = new NewStateTax();

    /**
     * Model tests for NewStateTax
     */
    @Test
    public void testNewStateTax() {
        // TODO: test NewStateTax
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'exemptions'
     */
    @Test
    public void exemptionsTest() {
        // TODO: test exemptions
    }

    /**
     * Test the property 'exemptions2'
     */
    @Test
    public void exemptions2Test() {
        // TODO: test exemptions2
    }

    /**
     * Test the property 'filingStatus'
     */
    @Test
    public void filingStatusTest() {
        // TODO: test filingStatus
    }

    /**
     * Test the property 'grossWagePercentage'
     */
    @Test
    public void grossWagePercentageTest() {
        // TODO: test grossWagePercentage
    }

    /**
     * Test the property 'percentage'
     */
    @Test
    public void percentageTest() {
        // TODO: test percentage
    }

    /**
     * Test the property 'primaryTax'
     */
    @Test
    public void primaryTaxTest() {
        // TODO: test primaryTax
    }

    /**
     * Test the property 'reciprocal'
     */
    @Test
    public void reciprocalTest() {
        // TODO: test reciprocal
    }

    /**
     * Test the property 'specialCheckCalc'
     */
    @Test
    public void specialCheckCalcTest() {
        // TODO: test specialCheckCalc
    }

    /**
     * Test the property 'taxCalcCode'
     */
    @Test
    public void taxCalcCodeTest() {
        // TODO: test taxCalcCode
    }

    /**
     * Test the property 'tCode'
     */
    @Test
    public void tCodeTest() {
        // TODO: test tCode
    }

}
