/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for NewWorkEligibility
 */
public class NewWorkEligibilityTest {
    private final NewWorkEligibility model = new NewWorkEligibility();

    /**
     * Model tests for NewWorkEligibility
     */
    @Test
    public void testNewWorkEligibility() {
        // TODO: test NewWorkEligibility
    }

    /**
     * Test the property 'alienOrAdmissionDocumentNbr'
     */
    @Test
    public void alienOrAdmissionDocumentNbrTest() {
        // TODO: test alienOrAdmissionDocumentNbr
    }

    /**
     * Test the property 'i9DateVerified'
     */
    @Test
    public void i9DateVerifiedTest() {
        // TODO: test i9DateVerified
    }

    /**
     * Test the property 'i9Notes'
     */
    @Test
    public void i9NotesTest() {
        // TODO: test i9Notes
    }

    /**
     * Test the property 'i9Verified'
     */
    @Test
    public void i9VerifiedTest() {
        // TODO: test i9Verified
    }

    /**
     * Test the property 'sSNDateVerified'
     */
    @Test
    public void sSNDateVerifiedTest() {
        // TODO: test sSNDateVerified
    }

    /**
     * Test the property 'sSNNotes'
     */
    @Test
    public void sSNNotesTest() {
        // TODO: test sSNNotes
    }

    /**
     * Test the property 'sSNVerified'
     */
    @Test
    public void sSNVerifiedTest() {
        // TODO: test sSNVerified
    }

    /**
     * Test the property 'visaType'
     */
    @Test
    public void visaTypeTest() {
        // TODO: test visaType
    }

    /**
     * Test the property 'workAuthorization'
     */
    @Test
    public void workAuthorizationTest() {
        // TODO: test workAuthorization
    }

    /**
     * Test the property 'workUntil'
     */
    @Test
    public void workUntilTest() {
        // TODO: test workUntil
    }

    /**
     * Test the property 'attestedDate'
     */
    @Test
    public void attestedDateTest() {
        // TODO: test attestedDate
    }

    /**
     * Test the property 'i94AdmissionNumber'
     */
    @Test
    public void i94AdmissionNumberTest() {
        // TODO: test i94AdmissionNumber
    }

    /**
     * Test the property 'foreignPassportNumber'
     */
    @Test
    public void foreignPassportNumberTest() {
        // TODO: test foreignPassportNumber
    }

    /**
     * Test the property 'countryOfIssuance'
     */
    @Test
    public void countryOfIssuanceTest() {
        // TODO: test countryOfIssuance
    }

}
