/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PayStatementDetails
 */
public class PayStatementDetailsTest {
    private final PayStatementDetails model = new PayStatementDetails();

    /**
     * Model tests for PayStatementDetails
     */
    @Test
    public void testPayStatementDetails() {
        // TODO: test PayStatementDetails
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'checkDate'
     */
    @Test
    public void checkDateTest() {
        // TODO: test checkDate
    }

    /**
     * Test the property 'det'
     */
    @Test
    public void detTest() {
        // TODO: test det
    }

    /**
     * Test the property 'detCode'
     */
    @Test
    public void detCodeTest() {
        // TODO: test detCode
    }

    /**
     * Test the property 'detType'
     */
    @Test
    public void detTypeTest() {
        // TODO: test detType
    }

    /**
     * Test the property 'eligibleCompensation'
     */
    @Test
    public void eligibleCompensationTest() {
        // TODO: test eligibleCompensation
    }

    /**
     * Test the property 'hours'
     */
    @Test
    public void hoursTest() {
        // TODO: test hours
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'transactionNumber'
     */
    @Test
    public void transactionNumberTest() {
        // TODO: test transactionNumber
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    public void transactionTypeTest() {
        // TODO: test transactionType
    }

    /**
     * Test the property 'year'
     */
    @Test
    public void yearTest() {
        // TODO: test year
    }

}
