/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PrimaryPayRate
 */
public class PrimaryPayRateTest {
    private final PrimaryPayRate model = new PrimaryPayRate();

    /**
     * Model tests for PrimaryPayRate
     */
    @Test
    public void testPrimaryPayRate() {
        // TODO: test PrimaryPayRate
    }

    /**
     * Test the property 'autoPay'
     */
    @Test
    public void autoPayTest() {
        // TODO: test autoPay
    }

    /**
     * Test the property 'baseRate'
     */
    @Test
    public void baseRateTest() {
        // TODO: test baseRate
    }

    /**
     * Test the property 'defaultHours'
     */
    @Test
    public void defaultHoursTest() {
        // TODO: test defaultHours
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'payFrequency'
     */
    @Test
    public void payFrequencyTest() {
        // TODO: test payFrequency
    }

    /**
     * Test the property 'payGrade'
     */
    @Test
    public void payGradeTest() {
        // TODO: test payGrade
    }

    /**
     * Test the property 'payType'
     */
    @Test
    public void payTypeTest() {
        // TODO: test payType
    }

    /**
     * Test the property 'ratePer'
     */
    @Test
    public void ratePerTest() {
        // TODO: test ratePer
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'salary'
     */
    @Test
    public void salaryTest() {
        // TODO: test salary
    }

}
