/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StateTax
 */
public class StateTaxTest {
    private final StateTax model = new StateTax();

    /**
     * Model tests for StateTax
     */
    @Test
    public void testStateTax() {
        // TODO: test StateTax
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'deductionsAmount'
     */
    @Test
    public void deductionsAmountTest() {
        // TODO: test deductionsAmount
    }

    /**
     * Test the property 'dependentsAmount'
     */
    @Test
    public void dependentsAmountTest() {
        // TODO: test dependentsAmount
    }

    /**
     * Test the property 'exemptions'
     */
    @Test
    public void exemptionsTest() {
        // TODO: test exemptions
    }

    /**
     * Test the property 'exemptions2'
     */
    @Test
    public void exemptions2Test() {
        // TODO: test exemptions2
    }

    /**
     * Test the property 'filingStatus'
     */
    @Test
    public void filingStatusTest() {
        // TODO: test filingStatus
    }

    /**
     * Test the property 'higherRate'
     */
    @Test
    public void higherRateTest() {
        // TODO: test higherRate
    }

    /**
     * Test the property 'otherIncomeAmount'
     */
    @Test
    public void otherIncomeAmountTest() {
        // TODO: test otherIncomeAmount
    }

    /**
     * Test the property 'percentage'
     */
    @Test
    public void percentageTest() {
        // TODO: test percentage
    }

    /**
     * Test the property 'specialCheckCalc'
     */
    @Test
    public void specialCheckCalcTest() {
        // TODO: test specialCheckCalc
    }

    /**
     * Test the property 'taxCalculationCode'
     */
    @Test
    public void taxCalculationCodeTest() {
        // TODO: test taxCalculationCode
    }

    /**
     * Test the property 'taxCode'
     */
    @Test
    public void taxCodeTest() {
        // TODO: test taxCode
    }

    /**
     * Test the property 'w4FormYear'
     */
    @Test
    public void w4FormYearTest() {
        // TODO: test w4FormYear
    }

}
