/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TrackingNumberResponse
 */
public class TrackingNumberResponseTest {
    private final TrackingNumberResponse model = new TrackingNumberResponse();

    /**
     * Model tests for TrackingNumberResponse
     */
    @Test
    public void testTrackingNumberResponse() {
        // TODO: test TrackingNumberResponse
    }

    /**
     * Test the property 'trackingNumber'
     */
    @Test
    public void trackingNumberTest() {
        // TODO: test trackingNumber
    }

}
