/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * The Local Tax model
 */
@ApiModel(description = "The Local Tax model")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LocalTax {
  public static final String SERIALIZED_NAME_EXEMPTIONS = "exemptions";
  @SerializedName(SERIALIZED_NAME_EXEMPTIONS)
  private Object exemptions;

  public static final String SERIALIZED_NAME_EXEMPTIONS2 = "exemptions2";
  @SerializedName(SERIALIZED_NAME_EXEMPTIONS2)
  private Object exemptions2;

  public static final String SERIALIZED_NAME_FILING_STATUS = "filingStatus";
  @SerializedName(SERIALIZED_NAME_FILING_STATUS)
  private Object filingStatus;

  public static final String SERIALIZED_NAME_RESIDENT_P_S_D = "residentPSD";
  @SerializedName(SERIALIZED_NAME_RESIDENT_P_S_D)
  private Object residentPSD;

  public static final String SERIALIZED_NAME_TAX_CODE = "taxCode";
  @SerializedName(SERIALIZED_NAME_TAX_CODE)
  private Object taxCode;

  public static final String SERIALIZED_NAME_WORK_P_S_D = "workPSD";
  @SerializedName(SERIALIZED_NAME_WORK_P_S_D)
  private Object workPSD;

  public LocalTax() {
  }

  public LocalTax exemptions(Object exemptions) {
    
    
    
    
    this.exemptions = exemptions;
    return this;
  }

   /**
   * Local tax exemptions value.&lt;br  /&gt;Decimal (12,2)
   * @return exemptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Local tax exemptions value.<br  />Decimal (12,2)")

  public Object getExemptions() {
    return exemptions;
  }


  public void setExemptions(Object exemptions) {
    
    
    
    this.exemptions = exemptions;
  }


  public LocalTax exemptions2(Object exemptions2) {
    
    
    
    
    this.exemptions2 = exemptions2;
    return this;
  }

   /**
   * Local tax exemptions 2 value.&lt;br  /&gt;Decimal (12,2)
   * @return exemptions2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Local tax exemptions 2 value.<br  />Decimal (12,2)")

  public Object getExemptions2() {
    return exemptions2;
  }


  public void setExemptions2(Object exemptions2) {
    
    
    
    this.exemptions2 = exemptions2;
  }


  public LocalTax filingStatus(Object filingStatus) {
    
    
    
    
    this.filingStatus = filingStatus;
    return this;
  }

   /**
   * Employee local tax filing status. Must match specific local tax setup. &lt;br  /&gt; Max length: 50
   * @return filingStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Employee local tax filing status. Must match specific local tax setup. <br  /> Max length: 50")

  public Object getFilingStatus() {
    return filingStatus;
  }


  public void setFilingStatus(Object filingStatus) {
    
    
    
    this.filingStatus = filingStatus;
  }


  public LocalTax residentPSD(Object residentPSD) {
    
    
    
    
    this.residentPSD = residentPSD;
    return this;
  }

   /**
   * Resident PSD (political subdivision code) applicable in PA. Must match Company setup.&lt;br  /&gt; Max length: 9
   * @return residentPSD
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Resident PSD (political subdivision code) applicable in PA. Must match Company setup.<br  /> Max length: 9")

  public Object getResidentPSD() {
    return residentPSD;
  }


  public void setResidentPSD(Object residentPSD) {
    
    
    
    this.residentPSD = residentPSD;
  }


  public LocalTax taxCode(Object taxCode) {
    
    
    
    
    this.taxCode = taxCode;
    return this;
  }

   /**
   * Local tax code.&lt;br  /&gt;Max length: 50
   * @return taxCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Local tax code.<br  />Max length: 50")

  public Object getTaxCode() {
    return taxCode;
  }


  public void setTaxCode(Object taxCode) {
    
    
    
    this.taxCode = taxCode;
  }


  public LocalTax workPSD(Object workPSD) {
    
    
    
    
    this.workPSD = workPSD;
    return this;
  }

   /**
   * Work location PSD. Must match Company setup. &lt;br  /&gt; Max length: 9
   * @return workPSD
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Work location PSD. Must match Company setup. <br  /> Max length: 9")

  public Object getWorkPSD() {
    return workPSD;
  }


  public void setWorkPSD(Object workPSD) {
    
    
    
    this.workPSD = workPSD;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LocalTax instance itself
   */
  public LocalTax putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocalTax localTax = (LocalTax) o;
    return Objects.equals(this.exemptions, localTax.exemptions) &&
        Objects.equals(this.exemptions2, localTax.exemptions2) &&
        Objects.equals(this.filingStatus, localTax.filingStatus) &&
        Objects.equals(this.residentPSD, localTax.residentPSD) &&
        Objects.equals(this.taxCode, localTax.taxCode) &&
        Objects.equals(this.workPSD, localTax.workPSD)&&
        Objects.equals(this.additionalProperties, localTax.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exemptions, exemptions2, filingStatus, residentPSD, taxCode, workPSD, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocalTax {\n");
    sb.append("    exemptions: ").append(toIndentedString(exemptions)).append("\n");
    sb.append("    exemptions2: ").append(toIndentedString(exemptions2)).append("\n");
    sb.append("    filingStatus: ").append(toIndentedString(filingStatus)).append("\n");
    sb.append("    residentPSD: ").append(toIndentedString(residentPSD)).append("\n");
    sb.append("    taxCode: ").append(toIndentedString(taxCode)).append("\n");
    sb.append("    workPSD: ").append(toIndentedString(workPSD)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("exemptions");
    openapiFields.add("exemptions2");
    openapiFields.add("filingStatus");
    openapiFields.add("residentPSD");
    openapiFields.add("taxCode");
    openapiFields.add("workPSD");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LocalTax
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LocalTax.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LocalTax is not found in the empty JSON string", LocalTax.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LocalTax.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LocalTax' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LocalTax> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LocalTax.class));

       return (TypeAdapter<T>) new TypeAdapter<LocalTax>() {
           @Override
           public void write(JsonWriter out, LocalTax value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LocalTax read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LocalTax instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LocalTax given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LocalTax
  * @throws IOException if the JSON string is invalid with respect to LocalTax
  */
  public static LocalTax fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LocalTax.class);
  }

 /**
  * Convert an instance of LocalTax to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

