/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.StagedEmployee;
import com.konfigthis.client.model.TrackingNumberResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeeStagingApi
 */
@Disabled
public class EmployeeStagingApiTest {

    private static EmployeeStagingApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new EmployeeStagingApi(apiClient);
    }

    /**
     * Add new employee to Web Link
     *
     * Add new employee to Web Link will send partially completed or potentially erroneous new hire record to Web Link, where it can be corrected and competed by company administrator or authorized Paylocity Service Bureau employee.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addNewEmployeeToWebLinkTest() throws ApiException {
        String companyId = null;
        List<Object> additionalDirectDeposit = null;
        List<Object> benefitSetup = null;
        Object birthDate = null;
        List<Object> customBooleanFields = null;
        List<Object> customDateFields = null;
        List<Object> customDropDownFields = null;
        List<Object> customNumberFields = null;
        List<Object> customTextFields = null;
        List<Object> departmentPosition = null;
        Object disabilityDescription = null;
        Object employeeId = null;
        Object ethnicity = null;
        List<Object> federalTax = null;
        Object firstName = null;
        Object fitwExemptReason = null;
        Object futaExemptReason = null;
        Object gender = null;
        List<Object> homeAddress = null;
        Object isEmployee943 = null;
        Object isSmoker = null;
        Object lastName = null;
        List<Object> localTax = null;
        List<Object> mainDirectDeposit = null;
        Object maritalStatus = null;
        Object medExemptReason = null;
        Object middleName = null;
        List<Object> nonPrimaryStateTax = null;
        Object preferredName = null;
        List<Object> primaryPayRate = null;
        List<Object> primaryStateTax = null;
        Object priorLastName = null;
        Object salutation = null;
        Object sitwExemptReason = null;
        Object ssExemptReason = null;
        Object ssn = null;
        List<Object> status = null;
        Object suffix = null;
        Object suiExemptReason = null;
        Object suiState = null;
        Object taxDistributionCode1099R = null;
        Object taxForm = null;
        Object veteranDescription = null;
        Object webTime = null;
        List<Object> workAddress = null;
        List<Object> workEligibility = null;
        List<TrackingNumberResponse> response = api.addNewEmployeeToWebLink(companyId)
                .additionalDirectDeposit(additionalDirectDeposit)
                .benefitSetup(benefitSetup)
                .birthDate(birthDate)
                .customBooleanFields(customBooleanFields)
                .customDateFields(customDateFields)
                .customDropDownFields(customDropDownFields)
                .customNumberFields(customNumberFields)
                .customTextFields(customTextFields)
                .departmentPosition(departmentPosition)
                .disabilityDescription(disabilityDescription)
                .employeeId(employeeId)
                .ethnicity(ethnicity)
                .federalTax(federalTax)
                .firstName(firstName)
                .fitwExemptReason(fitwExemptReason)
                .futaExemptReason(futaExemptReason)
                .gender(gender)
                .homeAddress(homeAddress)
                .isEmployee943(isEmployee943)
                .isSmoker(isSmoker)
                .lastName(lastName)
                .localTax(localTax)
                .mainDirectDeposit(mainDirectDeposit)
                .maritalStatus(maritalStatus)
                .medExemptReason(medExemptReason)
                .middleName(middleName)
                .nonPrimaryStateTax(nonPrimaryStateTax)
                .preferredName(preferredName)
                .primaryPayRate(primaryPayRate)
                .primaryStateTax(primaryStateTax)
                .priorLastName(priorLastName)
                .salutation(salutation)
                .sitwExemptReason(sitwExemptReason)
                .ssExemptReason(ssExemptReason)
                .ssn(ssn)
                .status(status)
                .suffix(suffix)
                .suiExemptReason(suiExemptReason)
                .suiState(suiState)
                .taxDistributionCode1099R(taxDistributionCode1099R)
                .taxForm(taxForm)
                .veteranDescription(veteranDescription)
                .webTime(webTime)
                .workAddress(workAddress)
                .workEligibility(workEligibility)
                .execute();
        // TODO: test validations
    }

}
