/*
 * WebLink API
 * For documentation about this API, please visit https://developer.paylocity.com/integrations/reference/weblink-overview
 *
 * The version of the OpenAPI document: v2
 * Contact: webservices@paylocity.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Onboarding;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OnboardingApi
 */
@Disabled
public class OnboardingApiTest {

    private static OnboardingApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new OnboardingApi(apiClient);
    }

    /**
     * Add Employee to Onboarding
     *
     * Onboarding API sends employee data into Paylocity Onboarding to help ensure an easy and accurate hiring process for subsequent completion into Paylocity Payroll/HR solution.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addEmployeeToOnboardingTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        String companyId = null;
        String employeeId = null;
        String address1 = null;
        String address2 = null;
        String autoPayType = null;
        Double baseRate = null;
        String city = null;
        String costCenter1 = null;
        String costCenter2 = null;
        String costCenter3 = null;
        Double defaultHours = null;
        String employeeStatus = null;
        String employmentType = null;
        String federalFilingStatus = null;
        String sex = null;
        String hireDate = null;
        String homePhone = null;
        String maritalStatus = null;
        String personalMobilePhone = null;
        String payFrequency = null;
        String personalEmailAddress = null;
        String payType = null;
        String ratePer = null;
        Double salary = null;
        String state = null;
        String ssn = null;
        String stateFilingStatus = null;
        String suiState = null;
        String taxForm = null;
        String taxState = null;
        String userName = null;
        String workEmailAddress = null;
        String zip = null;
        api.addEmployeeToOnboarding(firstName, lastName, companyId)
                .employeeId(employeeId)
                .address1(address1)
                .address2(address2)
                .autoPayType(autoPayType)
                .baseRate(baseRate)
                .city(city)
                .costCenter1(costCenter1)
                .costCenter2(costCenter2)
                .costCenter3(costCenter3)
                .defaultHours(defaultHours)
                .employeeStatus(employeeStatus)
                .employmentType(employmentType)
                .federalFilingStatus(federalFilingStatus)
                .sex(sex)
                .hireDate(hireDate)
                .homePhone(homePhone)
                .maritalStatus(maritalStatus)
                .personalMobilePhone(personalMobilePhone)
                .payFrequency(payFrequency)
                .personalEmailAddress(personalEmailAddress)
                .payType(payType)
                .ratePer(ratePer)
                .salary(salary)
                .state(state)
                .ssn(ssn)
                .stateFilingStatus(stateFilingStatus)
                .suiState(suiState)
                .taxForm(taxForm)
                .taxState(taxState)
                .userName(userName)
                .workEmailAddress(workEmailAddress)
                .zip(zip)
                .execute();
        // TODO: test validations
    }

}
